version: "3.0"
services:
 content:
  build: ./content_db_2
  env_file:
   - ./content_db/env
  environment:
   - INIT_DB=0
   - INIT_DATA=0
   - PGDATA=/var/lib/postgresql/data/pg_data
  expose:
   - "5432"
  ports:
   - "6001:5432"
  volumes:
   - ./.pg_data:/var/lib/postgresql/data/pg_data
  networks:
   - webnet
 redis:
  build: ./redis
  expose:
   - "6379"
  ports:
   - "6000:6379"
  volumes:
   - ./.redis_data:/data
  networks:
   - webnet
 etl:
  build: ./etl
  env_file:
   - ./etl/env
  environment:
   - INIT_REDIS=1
  command: python main.py #--nyt_begin '20181201' --nyt_end '20181205'
  volumes:
   - ./logs:/app/logs
  depends_on:
    - content
    - redis
  networks:
    - webnet

networks:
 webnet:
